language: cpp
cache: ccache
os: linux
compiler:
  - gcc
  - clang
env:
  - GCC_VERSION=5 LLVM_VERSION=4.0
  - GCC_VERSION=6 LLVM_VERSION=4.0
  - GCC_VERSION=6 LLVM_VERSION=3.8
  - GCC_VERSION=6 LLVM_VERSION=3.9
  - GCC_VERSION=6 LLVM_VERSION=5.0
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=5 LLVM_VERSION=4.0
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=3.8
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=3.9
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=5.0
sudo: required
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise-3.9
      - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'ppa:kalakris/eigen'
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - gfortran-4.9
      - gfortran-5
      - gfortran-6
      - clang-3.8
      - clang-3.9
      - clang-4.0
      - clang-5.0
      - libeigen3-dev
      - libboost1.55-dev
      - libblas-dev
      - liblapack-dev
      #- mpich2 # disallowed - build from source
      - libtbb-dev
      - cmake
      - cmake-data
#notifications:
#  email:
#    recipients:
#      - @github.com
#    on_success: change
#    on_failure: always
before_install: ./bin/dep-$TRAVIS_OS_NAME.sh
script: ./bin/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./_build/external/build/madness/CMakeFiles/CMakeOutput.log
  - cat ./_build/external/build/madness/CMakeFiles/CMakeError.log
  - cat ./_build/CMakeFiles/CMakeOutput.log
  - cat ./_build/CMakeFiles/CMakeError.log
